---
# Installe Docker et Docker Compose
- name: Vérifier si Docker est installé
  command: docker --version
  register: docker_installed
  ignore_errors: true
  changed_when: false

- name: Installer Docker si nécessaire
  apt:
    name: docker.io
    state: present
  when: docker_installed.rc != 0

- name: Vérifier si Docker Compose est installé
  command: /usr/local/bin/docker-compose --version
  register: docker_compose_installed
  ignore_errors: true
  changed_when: false

- name: Installer Docker Compose si nécessaire
  get_url:
    url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    mode: '0755'
  when: docker_compose_installed.rc != 0